### ISSUE TITLE
Accept Codecov API token as a provider argument

### ISSUE THREAD

**Issue by soulshake** [at-wat/terraform-provider-ucodecov#27]
Hello and thanks for this useful tool!

Would it be possible (or would a pull request be accepted) to make this provider accept the Codecov API token as an argument rather than getting it from an environment variable?

This would enable using a Terraform reference to provide the token, like

```
provider "ucodecov" {
  token = jsondecode(data.aws_secretsmanager_secret_version.codecov_secret.secret_string)["api-token"]
}
```

...similar to how it's implemented by [`terraform-provider-github`](https://github.com/integrations/terraform-provider-github/blob/1cb5703acae3ba391229bba43f1692cfd50178df/github/provider.go#L11).

Thanks!

**Comment by at-wat** [comment]
Sounds nice to have similar API (use env var as a default) to terraform-provider-github.
PR is welcome!
