### ISSUE TITLE
Build for darwin_arm64

### ISSUE THREAD

**Issue by christopher-dG** [at-wat/terraform-provider-ucodecov#33]
Hey there, would it be possible to publish a release that supports `darwin_arm64` (M1 Macs)?

**Comment by at-wat** [comment]
Seems that the last release was on Go 1.15 and `darwin_arm64` build requires Go 1.16.
https://github.com/goreleaser/goreleaser/issues/1952

**Comment by at-wat** [comment]
https://github.com/at-wat/terraform-provider-ucodecov/releases
![image](https://user-images.githubusercontent.com/8390204/121963431-10cb7800-cda5-11eb-8f2a-3752979df7a9.png)
`darwin_arm64` should be available now.

@christopher-dG could you try it?

**Comment by christopher-dG** [comment]
It worked, thank you for the quick response!
